service: streaming-bi
provider:
  name: aws
  runtime: python2.7
  cfLogs: true
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

package:
  exclude:
    - node_modules/**
    - venv

plugins:
  - serverless-wsgi
  - serverless-plugin-dotenv

custom:
  wsgi:
    app: handler.app
  dotenv:
    PHONE_MAPPING_TABLE_NAME: ${file(sensitive.yml):phoneMappingTableName}
    PHONE_RECORD_TABLE_NAME: ${file(sensitive.yml):phoneRecordTableName}
    TWILIO_ACCOUNT_SID: ${file(sensitive.yml):twilioAccountSid}
    TWILIO_AUTH_TOKEN: ${file(sensitive.yml):twilioAuthToken}
    VOICE_RESPONSE_URL: ${file(sensitive.yml):voiceResponseUrl}
    STATUS_CALLBACK_URL: ${file(sensitive.yml):statusCallbackUrl}

functions:
  api:
    handler: wsgi.handler
    events:
      - http:
          path: phone_number/list
          method: get
      - http:
          path: phone_number/list
          method: post
      - http:
          path: phone_number
          method: get
      - http:
          path: phone_number/{phone_number}
          method: put
      - http:
          path: phone_number/{phone_number}
          method: delete
      - http:
          path: phone_number/respond
          method: get
      - http:
          path: phone_number/record
          method: post

resources:
  Resources:
    phoneMappingTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
          - AttributeName: "PhoneNumber"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "PhoneNumber"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: ${file(sensitive.yml):phoneMappingTableName}
    phoneRecordTable:
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
          - AttributeName: "PhoneNumber"
            AttributeType: "S"
          - AttributeName: "Timestamp"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "PhoneNumber"
            KeyType: "HASH"
          - AttributeName: "Timestamp"
            KeyType: "RANGE"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: ${file(sensitive.yml):phoneRecordTableName}
