service: streaming-bi
provider:
  name: aws
  runtime: python2.7
  cfLogs: true
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"
        - "sqs:*"
        - "sns:*"
        - "sts:*"

plugins:
  - serverless-wsgi
  - serverless-plugin-dotenv

custom:
  wsgi:
    app: handler.app
  dotenv:
    TABLE_NAME: ${file(sensitive.yml):tableName}
    TWILIO_ACCOUNT_SID: ${file(sensitive.yml):twilioAccountSid}
    TWILIO_AUTH_TOKEN: ${file(sensitive.yml):twilioAuthToken}

functions:
  api:
    handler: wsgi.handler
    events:
      - http:
          path: phone_number/list
          method: get
      - http:
          path: phone_number/list
          method: post
      - http:
          path: phone_number
          method: get
      - http:
          path: phone_number/{sid}
          method: delete

resources:
  Resources:
    myDynamoDBTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
          - AttributeName: "PhoneNumber"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "PhoneNumber"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: ${file(sensitive.yml):tableName}