service: streaming-bi
provider:
  name: aws
  runtime: python2.7
  cfLogs: true
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

plugins:
  - serverless-wsgi

custom:
  streamName: ${opt:stage, self:provider.stage}BiStream
  wsgi:
    app: handler.app

functions:
  api:
    handler: wsgi.handler
    events:
      - http:
          path: rest
          method: post

resources:
  Resources:
    myDynamoDBTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
          - AttributeName: "AccountId"
            AttributeType: "S"
          - AttributeName: "Timestamp"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "AccountId"
            KeyType: "HASH"
          - AttributeName: "Timestamp"
            KeyType: "RANGE"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: ${self:custom.streamName}
        StreamSpecification: 
            StreamViewType: NEW_AND_OLD_IMAGES
